### ISSUE TITLE
Can I be your contributor

### ISSUE THREAD

**Issue by Mrcose** [Hax4us/Metasploit_termux#10]
Your script have a little error so I want to collaborate with you. My metasploit installer github is in https://github.com/41Team/MetasploitTermux . So can I collaborate with you?

**Comment by desged** [comment]
Yes but I haven't messed with this for months now.

**Comment by Mrcose** [comment]
Thank you
But I see a little bit a problem. Metasploit is not in latest version. So I
can fix it with reconfig your script. But I can make a complicated script
like you do. And I know how to make termux support the latest metasploit.
Thats why I want to be your contributor
