### ISSUE TITLE
Question about update 

### ISSUE THREAD

**Issue by Darkcast** [Hax4us/Metasploit_termux#12]
I see that you only mapped msfvenom and mfsconsole but not msfupdate. Is it possible to update it and how? 

Thanks

**Comment by Mrcose** [comment]
Probadly no because this repo install metasploit ```version 4.16.4``` and metasploit now is in version ```5.x.x``` . And the problem is termux not fully support the latest version. But I will try to make it support. Thanks for your feedback!

**Comment by Hax4us** [comment]
My script can install latest version now
