### ISSUE TITLE
27394 Segmentation Fault.... Why?? 

### ISSUE THREAD

**Issue by akiraaranii** [Hax4us/Metasploit_termux#13]
Can u help me?

**Comment by akiraaranii** [comment]
[1]    920 segmentation fault  msfconsole

**Comment by nikhilsuvarna89** [comment]
https://stackoverflow.com/questions/2346806/what-is-a-segmentation-fault

**Comment by MrNobodyTharusha** [comment]
Hey help me plzzz....

$ ./msfconsole
Segmentation fault
$

I reinstalled the termux but it didn't worked.

**Comment by nikhilsuvarna89** [comment]
> $ ./msfconsole
> Segmentation fault

https://github.com/rapid7/metasploit-framework/issues/8823#issue-249774522

**Comment by MrNobodyTharusha** [comment]
It does'nt work.

**Comment by nikhilsuvarna89** [comment]
> It does'nt work.

will you please post a screenshot rather than trying to express this verbally
