### ISSUE TITLE
Error when running 

### ISSUE THREAD

**Issue by Darkcast** [Hax4us/Metasploit_termux#16]
metasploit-credential not in the bundle, so Metasploit::Credential creation will fail for Msf::DBManager
/data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:25:in `rescue in optionally': undefined method `without' for #<Bundler::Settings:0x0000007e26a1a898> (NoMethodError)
	from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:20:in `optionally'
	from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:68:in `optionally_include_metasploit_credential_creation'
	from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:115:in `optionally_include_metasploit_credential_creation'
	from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:61:in `<class:DBManager>'
	from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:23:in `<top (required)>'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:61:in `<class:Framework>'
	from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:26:in `<module:Msf>'
	from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:18:in `<top (required)>'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core.rb:46:in `<top (required)>'
	from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
	from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
	from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
	from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
	from ./msfconsole:48:in `require'
	from ./msfconsole:48:in `<main>'
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require': dlopen failed: cannot locate symbol "rmpd_util_str_to_d" referenced by "/data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal/util.so"... - /data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal/util.so (LoadError)
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `<top (required)>'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_adapter.rb:3:in `<top (required)>'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activerecord-4.2.11/lib/active_record.rb:130:in `<module:ActiveRecord>'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activerecord-4.2.11/lib/active_record.rb:32:in `<top (required)>'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/metasploit_data_models-2.0.16/lib/metasploit_data_models.rb:15:in `<top (required)>'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/metasploit-credential-2.0.14/lib/metasploit/credential.rb:11:in `<top (required)>'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:22:in `optionally'
	from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:68:in `optionally_include_metasploit_credential_creation'
	from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:115:in `optionally_include_metasploit_credential_creation'
	from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:61:in `<class:DBManager>'
	from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:23:in `<top (required)>'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:61:in `<class:Framework>'
	from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:26:in `<module:Msf>'
	from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:18:in `<top (required)>'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
	from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core.rb:46:in `<top (required)>'
	from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
	from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
	from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
	from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
	from ./msfconsole:48:in `require'
	from ./msfconsole:48:in `<main>'

**Comment by ruthwik316** [comment]
Yes bro !
Solve it na !

**Comment by Hax4us** [comment]
Reinstall with updated script then issue should be resolved
