### ISSUE TITLE
msfconsole ruby error 

### ISSUE THREAD

**Issue by akg007** [Hax4us/Metasploit_termux#20]
$ msfconsole
Traceback (most recent call last):
ruby: no Ruby script found in input (LoadError)

Such error is coming please

**Comment by Hax4us** [comment]
Maybe metasploit is not downloaded properly so again try with stable internet

**Comment by mlkazd** [comment]
CANNOT LINK EXECUTABLE "ruby": library "/data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal.so" not found
Please help me!!

**Comment by Hax4us** [comment]
Script is updated now so reinstall
