### ISSUE TITLE
Help me NoMethodError

### ISSUE THREAD

**Issue by TooMann** [Hax4us/Metasploit_termux#21]
$ cd metasploit-framework
$ ./msfconsole
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: nokogiri.so: unused DT entry: type 0x6ffffef5 arg 0xb2c
metasploit-credential not in the bundle, so Metasploit::Credential creation will fail for Msf::DBManager
Traceback (most recent call last):
        36: from ./msfconsole:48:in `<main>'
        35: from ./msfconsole:48:in `require'
        34: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
        33: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
        32: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
        31: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
        30: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core.rb:46:in `<top (required)>'
        29: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
        28: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
        27: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:18:in `<top (required)>'
        26: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:26:in `<module:Msf>'
        25: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:61:in `<class:Framework>'
        24: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
        23: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
        22: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:23:in `<top (required)>'
        21: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:61:in `<class:DBManager>'
        20: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:115:in `optionally_include_metasploit_credential_creation'
        19: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:68:in `optionally_include_metasploit_credential_creation'
        18: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:22:in `optionally'
        17: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
        16: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
        15: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/metasploit-credential-2.0.14/lib/metasploit/credential.rb:11:in `<top (required)>'
        14: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
        13: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
        12: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/metasploit_data_models-2.0.16/lib/metasploit_data_models.rb:15:in `<top (required)>'
        11: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
        10: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
         9: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activerecord-4.2.11/lib/active_record.rb:32:in `<top (required)>'
         8: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activerecord-4.2.11/lib/active_record.rb:130:in `<module:ActiveRecord>'
         7: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
         6: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
         5: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_adapter.rb:3:in `<top (required)>'
         4: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
         3: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
         2: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `<top (required)>'
         1: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require': dlopen failed: cannot locate symbol "rmpd_util_str_to_d" referenced by "util.so"... - /data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal/util.so (LoadError)
        19: from ./msfconsole:48:in `<main>'
        18: from ./msfconsole:48:in `require'
        17: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
        16: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
        15: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
        14: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
        13: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core.rb:46:in `<top (required)>'
        12: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
        11: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
        10: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:18:in `<top (required)>'
         9: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:26:in `<module:Msf>'
         8: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:61:in `<class:Framework>'
         7: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
         6: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
         5: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:23:in `<top (required)>'
         4: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:61:in `<class:DBManager>'
         3: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:115:in `optionally_include_metasploit_credential_creation'
         2: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:68:in `optionally_include_metasploit_credential_creation'
         1: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:20:in `optionally'
/data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:25:in `rescue in optionally': undefined method `without' for #<Bundler::Settings:0xb3d20f88> (NoMethodError)

**Comment by Mrcose** [comment]
Are you cloning this repo with git?

**Comment by Hax4us** [comment]
Don't use directly `./msfconsole`. Just execute command `msfconsole`

**Comment by textnowid** [comment]
I am facing this problem.

Could not find nokogiri-1.10.3 in any of the sources
Run `bundle install` to install missing gems.

**Comment by sth2** [comment]
WARNING: linker: ruby: unused DT entry: type 0x6ffffef5 arg 0x45c
WARNING: linker: ruby: unused DT entry: type 0x1d arg 0x106
WARNING: linker: ruby: unused DT entry: type 0x6ffffffe arg 0x55c
WARNING: linker: ruby: unused DT entry: type 0x6fffffff arg 0x1
CANNOT LINK EXECUTABLE DEPENDENCIES: library "/data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal.so" not found

**Comment by sth2** [comment]
Run msfconsole problem
