### ISSUE TITLE
msfconsole is giving the same long error. Found no fix as of yet?

### ISSUE THREAD

**Issue by finnboyslim** [Hax4us/Metasploit_termux#24]
So the other day msfconsole was working fine. When I tried starting this up the day after it gave me this. I have tried so many fixes for this such as completely removing metasploit framework, reinstalling it, reinstalling Ruby. Checking for updates and upgrades within the Kali machine. I cannot find anything online about this error so this is my last resort.
When I type $msfvenom that works fine. I have also gone through every single folder in my computer associated with Metasploit and removed them... Nothing is working?

Traceback (most recent call last):
	34: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/bin/msfconsole:23:in `<main>'
	33: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/bin/msfconsole:23:in `load'
	32: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/metasploit-framework-4.17.52/msfconsole:49:in `<top (required)>'
	31: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/metasploit-framework-4.17.52/lib/metasploit/framework/command/base.rb:81:in `start'
	30: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/metasploit-framework-4.17.52/lib/metasploit/framework/command/base.rb:63:in `require_environment!'
	29: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/application.rb:328:in `require_environment!'
	28: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	27: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/backports-3.13.0/lib/backports/std_lib.rb:9:in `require_with_backports'
	26: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/backports-3.13.0/lib/backports/std_lib.rb:9:in `require'
	25: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/metasploit-framework-4.17.52/config/environment.rb:5:in `<top (required)>'
	24: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/railtie.rb:194:in `method_missing'
	23: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/railtie.rb:194:in `public_send'
	22: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/application.rb:352:in `initialize!'
	21: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:54:in `run_initializers'
	20: from /opt/metasploit/ruby/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	19: from /opt/metasploit/ruby/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	18: from /opt/metasploit/ruby/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	17: from /opt/metasploit/ruby/lib/ruby/2.5.0/tsort.rb:347:in `call'
	16: from /opt/metasploit/ruby/lib/ruby/2.5.0/tsort.rb:347:in `each'
	15: from /opt/metasploit/ruby/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	14: from /opt/metasploit/ruby/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	13: from /opt/metasploit/ruby/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	12: from /opt/metasploit/ruby/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	11: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	10: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:30:in `run'
	 9: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:30:in `instance_exec'
	 8: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
	 7: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/application/finisher.rb:56:in `each'
	 6: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/engine.rb:346:in `eager_load!'
	 5: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/engine.rb:469:in `eager_load!'
	 4: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/engine.rb:469:in `each'
	 3: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/engine.rb:471:in `block in eager_load!'
	 2: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/engine.rb:471:in `each'
	 1: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/wicked-0.5.0/app/controllers/wicked/wizard_controller.rb:5:in `<top (required)>': uninitialized constant ApplicationController (NameError)

Will greatly appreciate any help towards this. Thank you very much.

**Comment by Hax4us** [comment]
Reinstall with my updated script
