### ISSUE TITLE
Nokogiri Failed

### ISSUE THREAD

**Issue by Sayuk49** [Hax4us/Metasploit_termux#25]
Help me the nokogiri cannot install please help me.

**Comment by Hax4us** [comment]
I updated the script and issue should be resolved now

**Comment by nichu8** [comment]
still getting error

**Comment by Hax4us** [comment]
@nichu8 give screenshots along with your device info

**Comment by nichu8** [comment]
![IMG-20191114-WA0256](https://user-images.githubusercontent.com/50399699/68835459-2450c180-06de-11ea-9d0f-026d30ebc590.jpg)

**Comment by textnowid** [comment]
Me also having nokogiri problem pls solved this...

**Comment by Andrey2006615** [comment]
I have the same problem help us !!!

**Comment by radinmoradi** [comment]
در تاریخ شنبه ۱۶ نوامبر ۲۰۱۹،‏ ۱۹:۲۷ Andrey2006615 <notifications@github.com>
نوشت:

**Comment by koushik9652** [comment]
Even i'am also having the same problem. Help us from this

**Comment by Hax4us** [comment]
Script is updated now reinstall
