### ISSUE TITLE
Same like me..

### ISSUE THREAD

**Issue by arman11122** [Hax4us/Metasploit_termux#30]
Same like me..

CANNOT LINK EXECUTABLE "ruby": library "/data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal.so" not found

_Originally posted by @Capt123 in https://github.com/Hax4us/Metasploit_termux/issues/27#issuecomment-605709397_

**Comment by Hax4us** [comment]
I updated my script can you retest it ?
