### ISSUE TITLE
Proot handles 32 bit program only

### ISSUE THREAD

**Issue by RavanNaimish** [Hax4us/Metasploit_termux#31]
I was trying to install nethunter rootless but got this error

$ nh
proot error: '/data/data/com.termux/files/home/kali-arm64/usr/bin/env' is a 64-bit program whereas this version of proot handles 32-bit programs only
proot info: vpid 1: terminated with signal 11
Please help me

**Comment by Hax4us** [comment]
U installed 64bit kalifs but your phone supports only 32bit so this is obvious
