### ISSUE TITLE
Unable to use msfconsole

### ISSUE THREAD

**Issue by LaggyAcer404** [Hax4us/Metasploit_termux#32]
`$ msfconsole

Traceback (most recent call last):
ruby: no Ruby script found in input (LoadError)`

This part is the only part that failed to load for me, but the rest worked perfectly fine

**Comment by Hax4us** [comment]
Can show me screenshots of installing process ?

**Comment by LaggyAcer404** [comment]
![Screenshot_2020-04-24-20-16-21-47_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/64225470/80211594-93a4e700-8668-11ea-91c7-24104a8f2ada.png)
![Screenshot_2020-04-24-20-16-05-52_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/64225470/80211613-9bfd2200-8668-11ea-9ee5-2cfd3258369e.png)
![Screenshot_2020-04-24-20-16-10-79_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/64225470/80211616-9d2e4f00-8668-11ea-83ac-c5e44344cc45.png)
![Screenshot_2020-04-24-20-16-17-01_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/64225470/80211620-9dc6e580-8668-11ea-8752-dd2527f33bf4.png)
![Screenshot_2020-04-24-20-15-44-75_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/64225470/80211621-9e5f7c00-8668-11ea-898d-e6358c358a92.png)
![Screenshot_2020-04-24-20-15-58-56_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/64225470/80211624-9ef81280-8668-11ea-8cbe-619bea003ff1.png)

**Comment by LaggyAcer404** [comment]
important note: i was fiddling around on my screen while waiting for a response, i found out that doing this

`pkg install metasploit`

fixes whatever issue i was having with msfconsole but it left me with this error instead

`/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:84: warning: deprecated Object#=~ is called on Integer; it always return nil`

this error will always appear when i do msfconsole with that metasploit package i installed.

**Comment by Hax4us** [comment]
I think it's just a warning and msfconsole is working then you can ignore it

**Comment by LaggyAcer404** [comment]
Alright, thanks for replying my to concerns. I'll close the issue though I find it a bit funny that I have to install metasploit package to get it somewhat working
