### ISSUE TITLE
My metasploit stuck on starting TCP handler.

### ISSUE THREAD

**Issue by hksharmaa26** [Hax4us/Metasploit_termux#36]
First time I used it ,it was working but now it always stuck here...
![Screenshot_20200504-075334](https://user-images.githubusercontent.com/34143126/80932284-7d232c00-8ddc-11ea-8074-5fc4444e580d.jpg)

**Comment by Hax4us** [comment]
Set your lhost to `0.0.0.0`

**Comment by hksharmaa26** [comment]
Not working...i used my local,0.0.0.0,and loop back ko for lhost
Not working at all.
Please check this...may be the problem is in the update
