### ISSUE TITLE
Problem when running msfconsole in android below nougat

### ISSUE THREAD

**Issue by shabasrahman7** [Hax4us/Metasploit_termux#37]
CANNOT LINK EXECUTABLE: library "/data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/bigdecimal.so" not found
page record for 0x7f795fe050 was not found (block_size=64)

**Comment by shashanksrivastav6666** [comment]
CANNOT LINK EXECUTABLE: library "/data/data/com.termux/files/usr/lib/ruby/2.7.0/arm-linux-androideabi/bigdecimal.so" not found
page record for 0xb6f1904c was not found (block_size=64) error in running msfconsole what i do

**Comment by Hax4us** [comment]
what's output of `ls /data/data/com.termux/files/usr/lib/ruby/2.7.0/arm-linux-androideabi/bigdecimal.so`

**Comment by shashanksrivastav6666** [comment]
cannot access '/data/data/com.termux/files/usr/lib/ruby/2.7.0/arm-linux-androideabi/bigdecimal.so': No such file or directory

**Comment by Hax4us** [comment]
@shashanksrivastav6666 it means that your ruby installation was got interrupted so do
`apt remove ruby` then
`apt install ruby`

**Comment by siddhpurakaran** [comment]
> usr

still it is giving cannot access '/data/data/com.termux/files/usr/lib/ruby/2.7.0/arm-linux-androideabi/bigdecimal.so': No such file or directory


this is termux-info output

$ termux-info                                     Packages CPU architecture:                        aarch64                                           Subscribed repositories:                          # sources.list                                    deb https://termux.net stable main                # science-repo (sources.list.d/science.list)      deb https://dl.bintray.com/grimler/science-packages-21 science stable                               # game-repo (sources.list.d/game.list)            deb https://dl.bintray.com/grimler/game-packages-21 games stable                                    Updatable packages:                               All packages up to date                           Android version:                                  6.0.1                                             Kernel build information:                         Linux localhost 3.18.24-perf-g11631c9-01499-gde61539 #1 SMP PREEMPT Mon Aug 6 18:27:37 CST 2018 aarch64 Android

**Comment by Hax4us** [comment]
I got it. Somehy Your phone's architecture was detected wrong.
Give output following commands
1. `uname -m`
2. `getprop ro.product.cpu.abi`

**Comment by siddhpurakaran** [comment]
$ uname -m
aarch64
$ getprop ro.product.cpu.abi
arm64-v8a

**Comment by Hax4us** [comment]
what's output of `cat $PREFIX/bin/msfconsole`

**Comment by siddhpurakaran** [comment]
5 minute,  i cleared data of termux so running metasploit installation again

**Comment by siddhpurakaran** [comment]
cat $PREFIX/bin/msfconsole                      #!/data/data/com.termux/files/usr/bin/sh          SCRIPT_NAME=$(basename "$0")                      METASPLOIT_PATH="${HOME}/metasploit-framework"    # Fix ruby bigdecimal extensions linking error.   case "$(uname -m)" in                                     aarch64)                                                  export LD_PRELOAD="${PREFIX}/lib/ruby/2.7.0/aarch64-linux-android/bigdecimal.so:$LD_PRELOAD"                                                          ;;                                        arm*)                                                     export LD_PRELOAD="${PREFIX}/lib/ruby/2.7.0/arm-linux-androideabi/bigdecimal.so:$LD_PRELOAD"                                                          ;;                                        i686)                                                     export LD_PRELOAD="${PREFIX}/lib/ruby/2.7.0/i686-linux-android/bigdecimal.so:$LD_PRELOAD"                                                             ;;                                        x86_64)                                                   export LD_PRELOAD="${PREFIX}/lib/ruby/2.7.0/x86_64-linux-android/bigdecimal.so:$LD_PRELOAD"                                                           ;;                                        *)                                                        ;;                                esac                                              case "$SCRIPT_NAME" in                                    msfconsole|msfvenom)                                      exec ruby "$METASPLOIT_PATH/$SCRIPT_NAME" "$@"                                                      ;;                                        *)                                                        echo "[!] Unknown Metasploit command '$SCRIPT_NAME'."                                               exit 1                                            ;;

**Comment by Hax4us** [comment]
So try `msfconsole` command

**Comment by siddhpurakaran** [comment]
both msfvenom and msfconsole giving same error shown in above screenshot.

you can refresh page because i edited comment

**Comment by Hax4us** [comment]
Your metasploit is not installed properly can i see all screenshots from starting after `./metasploit.sh`

**Comment by siddhpurakaran** [comment]
there was some error during downloading ruby dependency (error was EOF unexpectedly and that file was about of 40MB)

1
![Screenshot_2020-05-18-15-41-25-38](https://user-images.githubusercontent.com/28296673/82201819-8d7bf080-991e-11ea-8e3d-c46da2d2acfc.png)

2
![Screenshot_2020-05-18-15-42-35-24](https://user-images.githubusercontent.com/28296673/82201874-9ff62a00-991e-11ea-81fa-e506c1682c0e.png)

3
![Screenshot_2020-05-18-15-43-39-14](https://user-images.githubusercontent.com/28296673/82201903-ad131900-991e-11ea-9a96-23560c4ccb84.png)

4
![Screenshot_2020-05-18-15-44-17-59](https://user-images.githubusercontent.com/28296673/82201923-b7cdae00-991e-11ea-9227-079fb5807fe1.png)

**Comment by siddhpurakaran** [comment]
logs before this was automatically deleted by termux

**Comment by Hax4us** [comment]
> there was some error during downloading ruby dependency (error was EOF unexpectedly and that file was about of 40MB)
That's issue 
So download it 
`curl -LO https://github.com/rapid7/metasploit-framework/archive/5.0.83.tar.gz`
And let me know if file was downloaded or not

**Comment by siddhpurakaran** [comment]
file downloaded successfully but after that also msfconsole giving same error.

$ msfconsole
CANNOT LINK EXECUTABLE: library "/data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/bigdecimal.so" not found
page record for 0x7fa81f0050 was not found (block_size=64)

**Comment by siddhpurakaran** [comment]
i also tried this commands but it is not soving problem. it also has warning while deleting ruby

![Screenshot_2020-05-18-16-09-08-66](https://user-images.githubusercontent.com/28296673/82204225-22ccb400-9922-11ea-882d-648eab03435a.png)

**Comment by Hax4us** [comment]
1. Clean old files `rm -rf $HOME/metasploit-framework`
2. A screenshot of downloaded file ( means output of above given command i.e `curl -L ....`)
3. Now extract the tar file `tar xf 5.0.83.tar.gz`
4. change directory name `mv metasploit-framework-5.0.83 metasploit-framework`
5. Go inside and install all gems `cd metasploit-framework && gem install --no-document rubygems-update && update_rubygems && gem install --no-document bundler:1.17.3 && bundle config build.nokogiri --use-system-libraries && bundle install -j4`
6. Some fixes `find $HOME/metasploit-framework -type f -executable -print0 | xargs -0 -r termux-fix-shebang && find "$PREFIX"/lib/ruby/gems -type f -iname \*.so -print0 | xargs -0 -r termux-elf-cleaner`

NOW TRY `msfconsole`

**Comment by Hax4us** [comment]
Oo wait what ? i noticed one thing that your android is < 7 , am i right ?

**Comment by siddhpurakaran** [comment]
yes i have android 6.0.1 😅

$ ls $PREFIX/lib/ruby
2.6.0  gems  site_ruby

**Comment by Hax4us** [comment]
That was the problem and i was looking for solutions from my script . Well then after all above steps just do one more additional step 
`sed -i s/2.7.0/2.6.0/ $(which msfconsole)`

**Comment by siddhpurakaran** [comment]
ohhh yesss

finally it is done.
Thank you so much.

**Comment by shashanksrivastav6666** [comment]
![Screenshot_20200520-164147](https://user-images.githubusercontent.com/59949038/82468122-168e5580-9ae0-11ea-9c78-81abbd00d001.png)
msfconsole not running

**Comment by shashanksrivastav6666** [comment]
please make a metasploit script for android 6.0.1

**Comment by Hax4us** [comment]
@shashanksrivastav6666 done. Just rerun my script.

**Comment by shashanksrivastav6666** [comment]
![Screenshot_20200523-184122](https://user-images.githubusercontent.com/59949038/82731528-35c9f480-9d25-11ea-9f0a-91ac3b0302f0.png)
HiddenEye is not running

**Comment by effkayrl** [comment]
Hey bro can you give me the command for metasploit installation for 
Android 6.01??

**Comment by anonymousPhp** [comment]
![Screenshot_20210210-115029](https://user-images.githubusercontent.com/63645868/107473388-a1dfd780-6b96-11eb-9945-d3ad2d9ce30f.png)

**Comment by ismado** [comment]
Hello, i have andriod v10 unrooted, i try to install metasploit in my termux it seems not working ryt, coz when I do msfconsole it gives me this error

CANNOT LINK EXECUTABLE "ruby": library "/data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/bigdecimal.so" not found

**Comment by suman5179** [comment]
> Hello, i am too having andriod v10 unrooted, i try to install metasploit in my termux it seems not working ryt, coz when I do msfconsole it gives me this error
> 
> CANNOT LINK EXECUTABLE "ruby": library "/data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/bigdecimal.so" not found.
So please help🙏

**Comment by Qtada** [comment]
Hi  , ive the same problem,  its tell me to install ruby-2.6.6 which i cant find , am using android 8

**Comment by MdRaihanAhmed-coder** [comment]
Hi,, I am facing the same problem. Using Android 11. I have gone through all of the codes you suggested above. But still it's showing the same error.

~/metasploit-framework $ msfconsole
CANNOT LINK EXECUTABLE "ruby": library "/data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/bigdecimal.so" not found: needed by main executable

![image](https://user-images.githubusercontent.com/26908164/110968304-8cbabc00-8381-11eb-88ff-6eb298865c29.png)

Please help, I am trying to install Metasploit for a couple of weeks.

**Comment by Hax4us** [comment]
join us on https://t.me/hax4us_group

**Comment by MrCuei** [comment]
I'm also in need of help.... Mine is Android 10 and is giving this problem - CANNOT LINK EXECUTABLE "ruby": library "/data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/bigdecimal.so" not found - if you can tell me what I have to do, I would appreciate it very much

**Comment by doule1** [comment]
> ohhh oui
> 
> enfin c'est fait.
> Merci beaucoup.



> ohhh oui
> 
> enfin c'est fait.
> Merci beaucoup.

hi brother it's been 3 days I have the same problem that you had last year I did everything but I can not solve the problem you can help me?
WHEN EXJECTS msfconsole) THE ANSWER IS: /data/data/com.termux/files/usr/bin/msfconsole: 31: exec: ruby: not found

**Comment by MdRaihanAhmed-coder** [comment]
> > ohhh oui
> > enfin c'est fait.
> > Merci beaucoup.
> 
> > ohhh oui
> > enfin c'est fait.
> > Merci beaucoup.
> 
> hi brother it's been 3 days I have the same problem that you had last year I did everything but I can not solve the problem you can help me?
> WHEN EXJECTS msfconsole) THE ANSWER IS: /data/data/com.termux/files/usr/bin/msfconsole: 31: exec: ruby: not found


You can try the following, if it doesn't work then drop a message in here,
1. Clear the storage and cache of termux,, 
2. give it storage permission
3. run this code: bash <(curl -fsSL "https://git.io/abhacker-repo") --install ruby=2.7.2 metasploit

It will work, I hope...

**Comment by suman5179** [comment]
> > ohhh oui
> > 
> > enfin c'est fait.
> > Merci beaucoup.
> 
> 
> 
> > ohhh oui
> > 
> > enfin c'est fait.
> > Merci beaucoup.
> 
> hi brother it's been 3 days I have the same problem that you had last year I did everything but I can not solve the problem you can help me?
> WHEN EXJECTS msfconsole) THE ANSWER IS: /data/data/com.termux/files/usr/bin/msfconsole: 31: exec: ruby: not found


Hey bro!! Copy-paste all the following commands one by one and give permission Yes where required you will get your problem solved before that you have to clear data of termux or you can reinstall termux then run the following :-

termux-setup-storage -y

apt install git -y

apt install wget -y

apt install curl -y

apt update -y

apt upgrade -y

bash <(curl -fsSL
 "https://git.io/termuxblack") -i && apt install ruby2 -y

bash <(curl -fsSL "https://git.io/metasploit-installer") -y

bash <(curl -fsSL "https://git.io/tcolors") -c 1 -y

I Guess there would  not any error after this!

**Comment by avci21** [comment]
> @shashanksrivastav6666 , Ruby kurulumunuzun kesintiye uğradığı anlamına gelir,
> `apt remove ruby`o zaman yapın
> `apt install ruby`
> Ve sonra bu komutu tekrar deneyin
> `ls /data/data/com.termux/files/usr/lib/ruby/2.7.0/arm-linux-androideabi/bigdecimal.so`
> 
> Ve bu komutun ekran görüntüsünü de verin
> `termux-info`
![Screenshot_2021-09-13-06-51-59-180_com termux](https://user-images.githubusercontent.com/90591274/133021845-28255cf5-ec1c-44aa-ab2f-cd783e0249eb.jpg)

**Comment by avci21** [comment]
msfconsole metaploit I can't help me

**Comment by jvsajv** [comment]
> > > ohhh oui
> > > enfin c'est fait.
> > > Merci beaucoup.
> > 
> > > ohhh oui
> > > enfin c'est fait.
> > > Merci beaucoup.
> > 
> > hi brother it's been 3 days I have the same problem that you had last year I did everything but I can not solve the problem you can help me?
> > WHEN EXJECTS msfconsole) THE ANSWER IS: /data/data/com.termux/files/usr/bin/msfconsole: 31: exec: ruby: not found
> 
> 
> You can try the following, if it doesn't work then drop a message in here,
> 1. Clear the storage and cache of termux,, 
> 2. give it storage permission
> 3. run this code: bash <(curl -fsSL "https://git.io/abhacker-repo") --install ruby=2.7.2 metasploit
> 
> It will work, I hope...

Best script ever, just simple magic

**Comment by 11974** [comment]
Thanks hommie

**Comment by Royhit699** [comment]
> @shashanksrivastav6666 it means that your ruby installation was got interrupted so do `apt remove ruby` then `apt install ruby` And then again try this command `ls /data/data/com.termux/files/usr/lib/ruby/2.7.0/arm-linux-androideabi/bigdecimal.so`
> 
> And give screenshot of this command also `termux-info`

![Screenshot_20230310-090146](https://user-images.githubusercontent.com/123624543/224216480-3164ae1d-a594-4e37-92df-ee980ad1a31c.jpg)
