### ISSUE TITLE
Why remove rbnacl

### ISSUE THREAD

**Issue by myfreess** [Hax4us/Metasploit_termux#4]

**Comment by Hax4us** [comment]
Sorry ?

**Comment by myfreess** [comment]
Sorry,I am not good at English.Would you like to write a wiki for this script?

**Comment by Hax4us** [comment]
Script is written in very simple way ...what type of information u want

**Comment by desged** [comment]
I apologize, my 3 year old must have had my phone and posted. Sorry if
there was any inconvenience.

**Comment by myfreess** [comment]
I can't successfully use any script to install metasploit, and the "force install rbreadline" of the termux official wiki will destroy the Gemfile, and the installation of rbnacl-libsodium also fails.

**Comment by myfreess** [comment]
And your script doesn't have these two steps, so I hope you write a complete wiki
