### ISSUE TITLE
ruby: no Ruby script found in input (Load Error)

### ISSUE THREAD

**Issue by dmonium** [Hax4us/Metasploit_termux#43]
I've installed following the instructions and got this message when I execute the command
msfconsole

Traceback (most recent call last):
ruby: no Ruby script found in input (Load Error)

Could you help me with this issue?

---
If you have this issue
I've found a better solution to install

git clone github.com/noob-hackers/m-wiz

**Comment by termux73** [comment]
No

**Comment by Destroyer179** [comment]
How to fixed this error

**Comment by Destroyer179** [comment]
> I've installed following the instructions and got this message when I execute the command
> msfconsole
> 
> Traceback (most recent call last):
> ruby: no Ruby script found in input (Load Error)
> 
> Could you help me with this issue?
> 
> If you have this issue
> I've found a better solution to install
> 
> git clone github.com/noob-hackers/m-wiz

Not working

**Comment by Hax4us** [comment]
@Destroyer179 whats your issue ? give all Screenshots while installation

**Comment by Destroyer179** [comment]
> @Destroyer179 whats your issue ? give all Screenshots while installation

![Screenshot_2020-08-01-11-45-20-801_com.termux.png](https://user-images.githubusercontent.com/68833824/89095645-92185700-d3ed-11ea-81da-be756d6f2c72.png)
this problem

**Comment by Hax4us** [comment]
please follow instructions from here `https://github.com/Hax4us/Metasploit_termux/blob/master/README.md#steps-for-metasploit`
and then take all Screenshots  and give here

**Comment by Destroyer179** [comment]
> please follow instructions from here https://github.com/Hax4us/Metasploit_termux/blob/master/README.md#steps-for-metasploit
> and then take all Screenshots  and give here 

Same aara

**Comment by Hax4us** [comment]
> > please follow instructions from here https://github.com/Hax4us/Metasploit_termux/blob/master/README.md#steps-for-metasploit
> > and then take all Screenshots  and give here
> 
> Same aara

i can't help without Screenshots

**Comment by Destroyer179** [comment]
U sent me ur insta id i will fully explained in insta

**Comment by Hax4us** [comment]
closing because of no response

**Comment by RumbunctiousRameez** [comment]
same error

**Comment by RumbunctiousRameez** [comment]
![Screenshot_20220324-213219](https://user-images.githubusercontent.com/99613853/159965077-560767b5-44d9-408b-9bbe-bad852e95dbf.png

**Comment by Nimachm** [comment]
> please follow instructions from here https://github.com/Hax4us/Metasploit_termux/blob/master/README.md#steps-for-metasploit
> and then take all Screenshots  and give here 

Run `bundle install` to install missing gems.
this error :/

**Comment by Nimachm** [comment]
what's Gemfile???
