### ISSUE TITLE
Can't run metasploit from the outside of metasploit-framework dir.

### ISSUE THREAD

**Issue by EasyDev-11436** [Hax4us/Metasploit_termux#53]
The binary file is contain html code.

When i run it through msfconsole it shows like this

![Screenshot_20210209_115722](https://user-images.githubusercontent.com/62865742/107318102-9032fd00-6ace-11eb-9dae-961e65a49cb8.jpg)

But i when i run it from the inside of metasploit-framework dir it's working without any problem.

![Screenshot_20210209_120357](https://user-images.githubusercontent.com/62865742/107318250-ec961c80-6ace-11eb-8c17-7452b8a9432f.jpg)

**Comment by Hax4us** [comment]
fixed now
