### ISSUE TITLE
metasploit ruby bigdecimal.so

### ISSUE THREAD

**Issue by Ieqzya** [Hax4us/Metasploit_termux#54]
![Screenshot_20210211-010742_Termux](https://user-images.githubusercontent.com/25486913/107579015-92e43e00-6c05-11eb-8941-4b73e5592165.jpg)
![Screenshot_20210211-010738_Termux](https://user-images.githubusercontent.com/25486913/107579017-94156b00-6c05-11eb-9f98-66037521b577.jpg)

metasploit-framework  metasploit.sh                     $ msfconsole                                            CANNOT LINK EXECUTABLE "ruby": library "/data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/bigdecimal.so" not found                                   $

**Comment by Ieqzya** [comment]
Try this, but not help...
![Screenshot_20210211-012411_Chrome.jpg](https://user-images.githubusercontent.com/25486913/107580640-e788b880-6c07-11eb-8731-7a047900c777.jpg)

**Comment by Ieqzya** [comment]
![Screenshot_20210211-021921_Termux.jpg](https://user-images.githubusercontent.com/25486913/107585591-9aa8e000-6c0f-11eb-8f83-c5b537ec431f.jpg)

**Comment by Ieqzya** [comment]
if i use bundle install![Screenshot_20210211-022238_Termux.jpg](https://user-images.githubusercontent.com/25486913/107585960-2458ad80-6c10-11eb-90c5-d0388343b76a.jpg)

**Comment by ankit383** [comment]
CANNOT LINK EXECUTABLE "ruby": library "/data/data/com.termux/files/usr/lib/ruby/3.0.0/aarch64-linux-android/bigdecimal.so" not found

**Comment by anishu88** [comment]
![Screenshot_2021-02-15-05-58-31-248_com termux](https://user-images.githubusercontent.com/79065450/107893740-e088df80-6f52-11eb-868a-50fbdbceb7e7.jpg)
@Hax4us 
I use ur command but still I have a issue please help 
Can u plz give me script of metasploit which has install without error

**Comment by avistnm** [comment]
> ![Screenshot_2021-02-15-05-58-31-248_com termux](https://user-images.githubusercontent.com/79065450/107893740-e088df80-6f52-11eb-868a-50fbdbceb7e7.jpg)
> @Hax4us 
> I use ur command but still I have a issue please help 
> Can u plz give me script of metasploit which has install without error 

Bro u can use the code developed by me
You can get it here - https://github.com/avistnm/Metasploit-avistnm.git
This will install metasploit framework without any error....

**Comment by Hax4us** [comment]
@avistnm see https://github.com/Hax4us/Metasploit_termux/issues/56
