### ISSUE TITLE
CANNOT LINK EXECUTABLE "createdb": library "/data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal.so" not found          CANNOT LINK EXECUTABLE "ruby": library "/data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal.so" not found

### ISSUE THREAD

**Issue by suriano998** [Hax4us/Metasploit_termux#64]
After typing msfconsole

CANNOT LINK EXECUTABLE "createdb": library "/data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal.so" not found          CANNOT LINK EXECUTABLE "ruby": library "/data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal.so" not found

It doesnt works, even though i installed termux black.

Please help and show exactly what to do.

**Comment by Hax4us** [comment]
what's your Android version ?

**Comment by suriano998** [comment]
> what's your Android version ?

9.0

**Comment by suriano998** [comment]
> what's your Android version ?

How Can I Fix It? My Android version 9
