### ISSUE TITLE
Metasploit Ruby bigdecimal.so

### ISSUE THREAD

**Issue by rendykyh** [Hax4us/Metasploit_termux#65]
its about CANNOT LINK EXECUTABLE, and i found msfconsole try to find "/data/data/com.termux/files/usr/lib/ruby/2.7.0/arm-linux-androideabi/bigdecimal.so" and my ruby show this "/data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/bigdecimal.so".. can i just copy/rename  "aarch64-linux-android" folder to "arm-linux-androideabi"?

**Comment by rendykyh** [comment]
im using "ln -fs /data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/* ." and working

**Comment by suriano998** [comment]
> im using "ln -fs /data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/* ." and working

Doesnt works for me

**Comment by rendykyh** [comment]
> 
> 
> > im using "ln -fs /data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/* ." and working
> 
> Doesnt works for me

create folder "mkdir /data/data/com.termux/files/usr/lib/ruby/2.7.0/arm-linux-androideabi"
go to folder "cd /data/data/com.termux/files/usr/lib/ruby/2.7.0/arm-linux-androideabi"
execute "ln -fs /data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/* ."

**Comment by suriano998** [comment]
> > > im using "ln -fs /data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/* ." and working
> > 
> > 
> > Doesnt works for me
> 
> create folder "mkdir /data/data/com.termux/files/usr/lib/ruby/2.7.0/arm-linux-androideabi"
> go to folder "cd /data/data/com.termux/files/usr/lib/ruby/2.7.0/arm-linux-androideabi"
> execute "ln -fs /data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/* ."

mkdir /data/data/com.termux/files/usr/lib/ruby/2.7.0/arm-linux-androideabi

No such file or directory

**Comment by rendykyh** [comment]
> 
> 
> > > > im using "ln -fs /data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/* ." and working
> > > 
> > > 
> > > Doesnt works for me
> > 
> > 
> > create folder "mkdir /data/data/com.termux/files/usr/lib/ruby/2.7.0/arm-linux-androideabi"
> > go to folder "cd /data/data/com.termux/files/usr/lib/ruby/2.7.0/arm-linux-androideabi"
> > execute "ln -fs /data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/* ."
> 
> mkdir /data/data/com.termux/files/usr/lib/ruby/2.7.0/arm-linux-androideabi
> 
> No such file or directory

before hacking you need some basic

**Comment by suriano998** [comment]
> > > > > im using "ln -fs /data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/* ." and working
> > > > 
> > > > 
> > > > Doesnt works for me
> > > 
> > > 
> > > create folder "mkdir /data/data/com.termux/files/usr/lib/ruby/2.7.0/arm-linux-androideabi"
> > > go to folder "cd /data/data/com.termux/files/usr/lib/ruby/2.7.0/arm-linux-androideabi"
> > > execute "ln -fs /data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/* ."
> > 
> > 
> > mkdir /data/data/com.termux/files/usr/lib/ruby/2.7.0/arm-linux-androideabi
> > No such file or directory
> 
> before hacking you need some basic

![Screenshot_20210308-104330](https://user-images.githubusercontent.com/59099065/110320196-3c093300-8010-11eb-8aa6-6de4e5fbbdd7.png)

I know the basics, your fix just dont works!!!
