### ISSUE TITLE
Error when executing ./msfconsole

### ISSUE THREAD

**Issue by ValentinoBalatti4** [Hax4us/Metasploit_termux#69]
![Screenshot_20210325-143957_Termux.png](https://user-images.githubusercontent.com/64121186/112518700-63822e80-8d78-11eb-8f63-6b01b67ae959.png)

OS: LineageOS 16.0 (Android 9)
ARCH: armv7l
Ruby: 2.7.2

I've had no problems installing the script or the gems, but when I try to execute ./msfconsole I get this error. I've already tried reinstalling the script and nothing happened.

**Comment by AlanDanielMatuzEnriquez** [comment]
What codes have you used could you show me?

**Comment by ValentinoBalatti4** [comment]
I installed the script with: wget https://raw.githubusercontent.com/Hax4us/Metasploit_termux/master/metasploit.sh 
And executed with ./metasploit.sh.
After that: cd metasploit-framework/bundle install.
I had some problems installing Nogogiri and pg gems, so I installed them individually. Lastly I tried to run msfconsole and the error showed up. I tried reinstalling but the error persists.

**Comment by AlanDanielMatuzEnriquez** [comment]
Have you already tried installing things together?

**Comment by ValentinoBalatti4** [comment]
I just did, everything seemed to work, until I executed 
./msfconsole and the same error showed up.
