### ISSUE TITLE
Error whilw run msfconsole

### ISSUE THREAD

**Issue by XSecr3t** [Hax4us/Metasploit_termux#7]
I have same issued in here

When i run msfconsole it show error :

> root@Mr.XSecr3t:~#msfconsole                       WARNING: linker: /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych.so: unused DT entry: type 0x6ffffef5 arg 0x4d0           Could not find nokogiri-1.8.0 in any of the sources 
Run `bundle install` to install missing gems.

And when i run bundle install result says :

> root@Mr.XSecr3t:~#bundle install                   WARNING: linker: Unsupported flags DT_FLAGS_1=0x8  WARNING: linker: Unsupported flags DT_FLAGS_1=0x8  
Could not locate Gemfile

I try to following some command and the result says :

> root@Mr.XSecr3t:~#gem install bundler; bundle      
WARNING: linker: /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych.so: unused DT entry: type 0x6ffffef5 arg 0x4d0          Successfully installed bundler-1.17.1              Parsing documentation for bundler-1.17.1
 Done installing documentation for bundler after 28 seconds
1 gem installed
Could not locate Gemfile

Still same error,what should i do? 
Help 
I cant use it again looks like useless for me :(

**Comment by XSecr3t** [comment]
@Hax4us 
Thanks for the reply

But error still show up 
Succes installed nokogiri 1.8.0 but error code still could not located gem file

> root@Mr.XSecr3t:~#gem install nokogiri -v 1.8.0 -- --use-system-libraries                             WARNING: linker: /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych.so: unused DT entry: type 0x6ffffef5 arg 0x4d0           WARNING: linker: Unsupported flags DT_FLAGS_1=0x8  WARNING: linker: Unsupported flags DT_FLAGS_1=0x8  Building native extensions with: '--use-system-libraries'                                             This could take a while...                         Successfully installed nokogiri-1.8.0              Parsing documentation for nokogiri-1.8.0           Installing ri documentation for nokogiri-1.8.0     Done installing documentation for nokogiri after 88 seconds                                           1 gem installed                                    root@Mr.XSecr3t:~#apt update && apt upgrade        WARNING: linker: Unsupported flags DT_FLAGS_1=0x8  WARNING: linker: Unsupported flags DT_FLAGS_1=0x8  WARNING: linker: Unsupported flags DT_FLAGS_1=0x8  WARNING: linker: Unsupported flags DT_FLAGS_1=0x8  WARNING: linker: Unsupported flags DT_FLAGS_1=0x8  WARNING: linker: Unsupported flags DT_FLAGS_1=0x8  WARNING: linker: Unsupported flags DT_FLAGS_1=0x8  WARNING: linker: Unsupported flags DT_FLAGS_1=0x8  Hit:1 https://termux.net stable InRelease          Hit:2 https://grimler.se root InRelease            Get:3 https://termux-x11.ml x11 InRelease [2296 B] Hit:3 https://termux-x11.ml x11 InRelease          Reading package lists... Done                      Building dependency tree                           Reading state information... Done                  All packages are up to date.                       Reading package lists... Done                      Building dependency tree                           Reading state information... Done
root@Mr.XSecr3t:~#bundle install                   WARNING: linker: Unsupported flags DT_FLAGS_1=0x8  WARNING: linker: Unsupported flags DT_FLAGS_1=0x8  
Could not locate Gemfile :(

**Comment by XSecr3t** [comment]
Another error show up when i run msfconsole

> Could not find recog-2.1.20 in any of the sources  
Run `bundle install` to install missing gems.

**Comment by Hax4us** [comment]
Make sure u r in metasploit folder otherwise gemfile error will come and If u r already in metasploit folder then check the gemfile is exists or not

**Comment by XSecr3t** [comment]
@Hax4us

Here's

 > root@Mr.XSecr3t:~#cd metasploit-framework          root@Mr.XSecr3t:~#ls                               CODE_OF_CONDUCT.md                                 CONTRIBUTING.md                                    COPYING                                            Dockerfile                                         Gemfile                                            Gemfile.local.example                              Gemfile.lock                                       LICENSE                                            LICENSE_GEMS                                       README.md                                          Rakefile                                           Vagrantfile                                        app                                                config                                             data                                               db                                                 docker                                             docker-compose.override.yml                        docker-compose.yml                                 documentation                                      external                                           lib                                                metasploit-framework.gemspec                       modules                                            msfconsole                                         msfd                                               msfrpc                                             msfrpcd                                            msfupdate                                          msfvenom                                           plugins                                            script
I think gemfile is exists but why error show up?

**Comment by Hax4us** [comment]
Give `bundle install` command in metasploit folder

**Comment by XSecr3t** [comment]
@Hax4us 

Seems works bundle install and successfullu fetch 12 gem files
But when i run msfconsole this error show up 
This time much error i dont know what 

> root@Mr.XSecr3t:~#msfconsole                       WARNING: linker: /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych.so: unused DT entry: type 0x6ffffef5 arg 0x4d0           WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.0/lib/nokogiri/nokogiri.so: unused DT entry: type 0x6ffffef5 arg 0xba0
WARNING: linker: /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/pcaprub-0.12.4/lib/pcaprub_c.so: unused DT entry: type 0x6ffffef5 arg 0x3e0
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/versions.rb:4: warning: already initialized constant Psych::VERSION
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/versions.rb:4: warning: previous definition of VERSION was here
/data/data/com.termux/files/usr/lib/ruby/2
h64-linux-android/psych.so: warning: already initialized constant Psych::Parser::ANY
/data/data/com.termux/files/usr/lib/ruby/2.5.0/aarch64-linux-android/psych.so: warning: already initialized constant Psych::Parser::UTF8
/data/data/com.termux/files/usr/lib/ruby/2.5.0/aarch64-linux-android/psych.so: warning: already initialized constant Psych::Parser::UTF16LE
/data/data/com.termux/files/usr/lib/ruby/2.5.0/aarch64-linux-android/psych.so: warning: already initialized constant Psych::Parser::UTF16BE
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:7: warning: already initialized constant Psych::ClassLoader::BIG_DECIMAL
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:7: warning: previous definition of BIG_DECIMAL was here   /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:8: warning: already initialized constant Psych::ClassLoader::COMPLEX
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:8: warning: previous definition of COMPLEX was here       /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:9: warning: already initialized constant Psych::ClassLoader::DATE
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:9: warning: previous definition of DATE was here          /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:10: warning: already initialized constant Psych::ClassLoader::DATE_TIME
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:10: warning: previous definition of DATE_TIME was here
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:11: warning: already initialized constant Psych::ClassLoader::EXCEPTION
0/gems/psych-3.0.3/lib/psych/class_loader.rb:11: warning: previous definition of EXCEPTION was here
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:12: warning: already initialized constant Psych::ClassLoader::OBJECT                /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:12: warning: previous definition of OBJECT was here
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:13: warning: already initialized constant Psych::ClassLoader::PSYCH_OMAP            /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:13: warning: previous definition of PSYCH_OMAP was here   /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:14: warning: already initialized constant Psych::ClassLoader::PSYCH_SET             /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:14: warning: previous definition of PSYCH_SET was here    /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:15: warning: already initialized constant Psych::ClassLoader::RANGE                 /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:15: warning: previous definition of RANGE was here        /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:16: warning: already initialized constant Psych::ClassLoader::RATIONAL              /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:16: warning: previous definition of RATIONAL was here     /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:17: warning: already initialized constant Psych::ClassLoader::REGEXP
0/gems/psych-3.0.3/lib/psych/class_loader.rb:17: warning: previous definition of REGEXP was here       /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:18: warning: already initialized constant Psych::ClassLoader::STRUCT                /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:18: warning: previous definition of STRUCT was here       /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:19: warning: already initialized constant Psych::ClassLoader::SYMBOL                /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:19: warning: previous definition of SYMBOL was here       /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:65: warning: already initialized constant Psych::ClassLoader::CACHE                 /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:65: warning: previous definition of CACHE was here        /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/scalar_scanner.rb:9: warning: already initialized constant Psych::ScalarScanner::TIME               /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/scalar_scanner.rb:9: warning: previous definition of TIME was here        /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/scalar_scanner.rb:12: warning: already initialized constant Psych::ScalarScanner::FLOAT             /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/scalar_scanner.rb:12: warning: previous definition of FLOAT was here      /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/scalar_scanner.rb:17: warning: already initialized constant Psych::ScalarScanner::INTEGER
0/gems/psych-3.0.3/lib/psych/scalar_scanner.rb:17: warning: previous definition of INTEGER was here    /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/stream.rb:13: warning: already initialized constant Psych::Nodes::Stream::ANY                 /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/stream.rb:13: warning: previous definition of ANY was here          /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/stream.rb:16: warning: already initialized constant Psych::Nodes::Stream::UTF8                /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/stream.rb:16: warning: previous definition of UTF8 was here         /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/stream.rb:19: warning: already initialized constant Psych::Nodes::Stream::UTF16LE             /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/stream.rb:19: warning: previous definition of UTF16LE was here      /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/stream.rb:22: warning: already initialized constant Psych::Nodes::Stream::UTF16BE             /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/stream.rb:22: warning: previous definition of UTF16BE was here      /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/sequence.rb:43: warning: already initialized constant Psych::Nodes::Sequence::ANY             /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/sequence.rb:43: warning: previous definition of ANY was here        /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/sequence.rb:46: warning: already initialized constant Psych::Nodes::Sequence::BLOCK
0/gems/psych-3.0.3/lib/psych/nodes/sequence.rb:46: warning: previous definition of BLOCK was here      /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/sequence.rb:49: warning: already initialized constant Psych::Nodes::Sequence::FLOW
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/sequence.rb:49: warning: previous definition of FLOW was here       /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/scalar.rb:10: warning: already initialized constant Psych::Nodes::Scalar::ANY
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/scalar.rb:10: warning: previous definition of ANY was here          /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/scalar.rb:13: warning: already initialized constant Psych::Nodes::Scalar::PLAIN
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/scalar.rb:13: warning: previous definition of PLAIN was here
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/scalar.rb:16: warning: already initialized constant Psych::Nodes::Scalar::SINGLE_QUOTED       /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/scalar.rb:16: warning: previous definition of SINGLE_QUOTED was here
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/scalar.rb:19: warning: already initialized constant Psych::Nodes::Scalar::DOUBLE_QUOTED
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/scalar.rb:19: warning: previous definition of DOUBLE_QUOTED was here
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/scalar.rb:22: warning: already initialized constant Psych::Nodes::Scalar::LITERAL
0/gems/psych-3.0.3/lib/psych/nodes/scalar.rb:22: warning: previous definition of LITERAL was here
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/scalar.rb:25: warning: already initialized constant Psych::Nodes::Scalar::FOLDED
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/scalar.rb:25: warning: previous definition of FOLDED was here
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/mapping.rb:17: warning: already initialized constant Psych::Nodes::Mapping::ANY               /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/mapping.rb:17: warning: previous definition of ANY was here
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/mapping.rb:20: warning: already initialized constant Psych::Nodes::Mapping::BLOCK
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/mapping.rb:20: warning: previous definition of BLOCK was here       /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/mapping.rb:23: warning: already initialized constant Psych::Nodes::Mapping::FLOW
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/mapping.rb:23: warning: previous definition of FLOW was here        /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/visitors/visitor.rb:11: warning: already initialized constant Psych::Visitors::Visitor::DISPATCH    /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/visitors/visitor.rb:11: warning: previous definition of DISPATCH was here
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/visitors/to_ruby.rb:334: warning: already initialized constant Psych::Visitors::ToRuby::SHOVEL
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/handler.rb:27: warning: already initialized constant Psych::Handler::OPTIONS                        /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/handler.rb:27: warning: previous definition of OPTIONS was here
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/handler.rb:30: warning: already initialized constant Psych::Handler::EVENTS
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/handler.rb:30: warning: previous definition of EVENTS was here
Traceback (most recent call last):
        37: from /data/data/com.termux/files/usr/bin/msfconsole:48:in `<main>'
        36: from /data/data/com.termux/files/usr/bin/msfconsole:48:in `require'
        35: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
        34: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
        33: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
        32: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
        31: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core.rb:46:in `<top (required)>'
30: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require_with_backports'
        29: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require'
        28: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:18:in `<top (required)>'
        27: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:26:in `<module:Msf>'
        26: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:64:in `<class:Framework>'
        25: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
        24: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
        23: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
22: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require_with_backports'
        21: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require'
        20: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/cert_provider.rb:2:in `<top (required)>'
        19: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
        18: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
        17: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
        16: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require_with_backports'
        15: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require'
        14: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/faker-1.8.7/lib/faker.rb:5:in `<top (required)>'
        13: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
12: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
        11: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
        10: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require_with_backports'                 9: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require'                                8: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych.rb:19:in `<top (required)>'
         7: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
         6: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'                                                           5: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
         4: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require_with_backports'
         3: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require'
2: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/parser.rb:2:in `<top (required)>'
         1: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/parser.rb:33:in `<module:Psych>'/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/parser.rb:34:in `<class:Parser>': superclass mismatch for class Mark (TypeError)

I dont know what is it

**Comment by picassotech** [comment]
msfconsole
[*] Metasploit requires the Bundler gem to be installed
    $ gem install bundler                          $ bundle install
Traceback (most recent call last):                         2: from /data/data/com.termux/files/usr/bin/bundle:23:in `<main>'                                     1: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path' /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException).


Error please solve it.plz help

**Comment by picassotech** [comment]
![screenshot_2019-01-10-18-42-38](https://user-images.githubusercontent.com/46565864/50996042-b9c17900-1542-11e9-899a-8fa9f937adcc.png)
![screenshot_2019-01-10-18-42-06](https://user-images.githubusercontent.com/46565864/50996043-ba5a0f80-1542-11e9-805f-a7a53909549a.png)
Lindly
![Uploading Screenshot_2019-01-10-18-42-02.png…]()  check error screenshot here

**Comment by iuio** [comment]
Help please #<Bundler::Settings:0xf452b140> (NoMethodError)

**Comment by Usr-Termux** [comment]
When I run msfconsole I get this error

Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
/data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require': dlopen failed: library "libandroid-support.so" not found: needed by /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bcrypt-3.1.16/lib/bcrypt_ext.so in namespace (default) - /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bcrypt-3.1.16/lib/bcrypt_ext.so (LoadError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bcrypt-3.1.16/lib/bcrypt.rb:12:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework.rb:9:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:88:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:88:in `rescue in block in require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:65:in `block in require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/config/application.rb:10:in `<top (required)>'
        from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:2:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:2:in `<top (required)>'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:17:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:17:in `<top (required)>'
        from ./msfconsole:18:in `require'
        from ./msfconsole:18:in `<main>'
/data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `require': cannot load such file -- metasploit-framework (LoadError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `block in require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/config/application.rb:10:in `<top (required)>'
        from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:2:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:2:in `<top (required)>'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:17:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:17:in `<top (required)>'
        from ./msfconsole:18:in `require'
        from ./msfconsole:18:in `<main>'
