### ISSUE TITLE
nokogiri-1.12.5 cant be installed

### ISSUE THREAD

**Issue by gk98s** [Hax4us/Metasploit_termux#89]
they published nokogiri 1.13.0 and for some reason nokogiri 1.12.5 cant be installed. and when i install 1.13.0 i still cant use metasploit it says "could not find nokogiri-1.12.5 in any of the sources"

**Comment by LxaNce-Hacker** [comment]
Yes

**Comment by LxaNce-Hacker** [comment]
Same problem
